// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqrRUjxty6iUdfnxywM9ZZ4DjA8AR_lNo',
    appId: '1:443622231935:web:2885933cc52a185f6ad44a',
    messagingSenderId: '443622231935',
    projectId: 'mobile-air-quality-app',
    authDomain: 'mobile-air-quality-app.firebaseapp.com',
    storageBucket: 'mobile-air-quality-app.firebasestorage.app',
    measurementId: 'G-1P0T63JBYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLhhnwUg8yr3XvIxtMHY-58W_xmRjzKpg',
    appId: '1:443622231935:android:906cbdcdff6d8e8a6ad44a',
    messagingSenderId: '443622231935',
    projectId: 'mobile-air-quality-app',
    storageBucket: 'mobile-air-quality-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaD5hLc1qkpPMut3nRfXeGIHsk_IY7nck',
    appId: '1:443622231935:ios:032db9411a5036d76ad44a',
    messagingSenderId: '443622231935',
    projectId: 'mobile-air-quality-app',
    storageBucket: 'mobile-air-quality-app.firebasestorage.app',
    iosBundleId: 'com.example.mobileAirQuality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaD5hLc1qkpPMut3nRfXeGIHsk_IY7nck',
    appId: '1:443622231935:ios:032db9411a5036d76ad44a',
    messagingSenderId: '443622231935',
    projectId: 'mobile-air-quality-app',
    storageBucket: 'mobile-air-quality-app.firebasestorage.app',
    iosBundleId: 'com.example.mobileAirQuality',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqrRUjxty6iUdfnxywM9ZZ4DjA8AR_lNo',
    appId: '1:443622231935:web:792a730c148a72d96ad44a',
    messagingSenderId: '443622231935',
    projectId: 'mobile-air-quality-app',
    authDomain: 'mobile-air-quality-app.firebaseapp.com',
    storageBucket: 'mobile-air-quality-app.firebasestorage.app',
    measurementId: 'G-91VQSJD2KX',
  );
}
